# Generated by Django 3.2.2 on 2021-06-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='logo_url',
            field=models.URLField(blank=True, verbose_name='Logo URL'),
        ),
    ]
