# Generated by Django 3.2.2 on 2021-06-07 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('subscription_start', models.DateTimeField(editable=False, verbose_name='Start date')),
                ('subscription_end', models.DateTimeField(editable=False, verbose_name='End date')),
                ('status', models.CharField(blank=True, editable=False, max_length=255, verbose_name='LiqPay status')),
                ('callback', models.JSONField(blank=True, default=dict, verbose_name='LiqPay callback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Subscriber')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
    ]
